development:
  db_hosts: ["127.0.0.1"]
  db_port: 9042
  db_username: ''
  db_password: ''
  db_keyspace: xadf

production:
  db_hosts: ["127.0.0.1"]
  db_port: 9042
  db_username: ''
  db_password: ''
  db_keyspace: xadf
